from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.history_list_bundle_inner import HistoryListBUNDLEInner
from openapi_server.models.history_list_ingame_inner import HistoryListINGAMEInner
from openapi_server import util

from openapi_server.models.history_list_bundle_inner import HistoryListBUNDLEInner  # noqa: E501
from openapi_server.models.history_list_ingame_inner import HistoryListINGAMEInner  # noqa: E501

class GetUserHistory200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """GetUserHistory200Response - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GetUserHistory200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_user_history_200_response of this GetUserHistory200Response.  # noqa: E501
        :rtype: GetUserHistory200Response
        """
        return util.deserialize_model(dikt, cls)
