from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Feedback(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, user_uuid=None, content=None, timestamp=None):  # noqa: E501
        """Feedback - a model defined in OpenAPI

        :param id: The id of this Feedback.  # noqa: E501
        :type id: float
        :param user_uuid: The user_uuid of this Feedback.  # noqa: E501
        :type user_uuid: str
        :param content: The content of this Feedback.  # noqa: E501
        :type content: str
        :param timestamp: The timestamp of this Feedback.  # noqa: E501
        :type timestamp: datetime
        """
        self.openapi_types = {
            'id': float,
            'user_uuid': str,
            'content': str,
            'timestamp': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'user_uuid': 'user_uuid',
            'content': 'content',
            'timestamp': 'timestamp'
        }

        self._id = id
        self._user_uuid = user_uuid
        self._content = content
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'Feedback':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Feedback of this Feedback.  # noqa: E501
        :rtype: Feedback
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> float:
        """Gets the id of this Feedback.

        Id of feedback.  # noqa: E501

        :return: The id of this Feedback.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this Feedback.

        Id of feedback.  # noqa: E501

        :param id: The id of this Feedback.
        :type id: float
        """

        self._id = id

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this Feedback.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this Feedback.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this Feedback.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this Feedback.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def content(self) -> str:
        """Gets the content of this Feedback.

        Actual feedback content.  # noqa: E501

        :return: The content of this Feedback.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this Feedback.

        Actual feedback content.  # noqa: E501

        :param content: The content of this Feedback.
        :type content: str
        """

        self._content = content

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this Feedback.

        Timestamp when user created feedback  # noqa: E501

        :return: The timestamp of this Feedback.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this Feedback.

        Timestamp when user created feedback  # noqa: E501

        :param timestamp: The timestamp of this Feedback.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
