from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAllFeedbacks200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content=None, feedback_id=None, timestamp=None):  # noqa: E501
        """GetAllFeedbacks200ResponseInner - a model defined in OpenAPI

        :param content: The content of this GetAllFeedbacks200ResponseInner.  # noqa: E501
        :type content: str
        :param feedback_id: The feedback_id of this GetAllFeedbacks200ResponseInner.  # noqa: E501
        :type feedback_id: int
        :param timestamp: The timestamp of this GetAllFeedbacks200ResponseInner.  # noqa: E501
        :type timestamp: datetime
        """
        self.openapi_types = {
            'content': str,
            'feedback_id': int,
            'timestamp': datetime
        }

        self.attribute_map = {
            'content': 'content',
            'feedback_id': 'feedback_id',
            'timestamp': 'timestamp'
        }

        self._content = content
        self._feedback_id = feedback_id
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'GetAllFeedbacks200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The getAllFeedbacks_200_response_inner of this GetAllFeedbacks200ResponseInner.  # noqa: E501
        :rtype: GetAllFeedbacks200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self) -> str:
        """Gets the content of this GetAllFeedbacks200ResponseInner.

        Feedback content.  # noqa: E501

        :return: The content of this GetAllFeedbacks200ResponseInner.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this GetAllFeedbacks200ResponseInner.

        Feedback content.  # noqa: E501

        :param content: The content of this GetAllFeedbacks200ResponseInner.
        :type content: str
        """

        self._content = content

    @property
    def feedback_id(self) -> int:
        """Gets the feedback_id of this GetAllFeedbacks200ResponseInner.

        Unique identifier of the feedback.  # noqa: E501

        :return: The feedback_id of this GetAllFeedbacks200ResponseInner.
        :rtype: int
        """
        return self._feedback_id

    @feedback_id.setter
    def feedback_id(self, feedback_id: int):
        """Sets the feedback_id of this GetAllFeedbacks200ResponseInner.

        Unique identifier of the feedback.  # noqa: E501

        :param feedback_id: The feedback_id of this GetAllFeedbacks200ResponseInner.
        :type feedback_id: int
        """

        self._feedback_id = feedback_id

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this GetAllFeedbacks200ResponseInner.

        Date and time when the feedback was created.  # noqa: E501

        :return: The timestamp of this GetAllFeedbacks200ResponseInner.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this GetAllFeedbacks200ResponseInner.

        Date and time when the feedback was created.  # noqa: E501

        :param timestamp: The timestamp of this GetAllFeedbacks200ResponseInner.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
