from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class HistoryListINGAMEInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, timestamp=None, credits=None, transaction_type=None):  # noqa: E501
        """HistoryListINGAMEInner - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this HistoryListINGAMEInner.  # noqa: E501
        :type user_uuid: str
        :param timestamp: The timestamp of this HistoryListINGAMEInner.  # noqa: E501
        :type timestamp: datetime
        :param credits: The credits of this HistoryListINGAMEInner.  # noqa: E501
        :type credits: int
        :param transaction_type: The transaction_type of this HistoryListINGAMEInner.  # noqa: E501
        :type transaction_type: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'timestamp': datetime,
            'credits': int,
            'transaction_type': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'timestamp': 'timestamp',
            'credits': 'credits',
            'transaction_type': 'transaction_type'
        }

        self._user_uuid = user_uuid
        self._timestamp = timestamp
        self._credits = credits
        self._transaction_type = transaction_type

    @classmethod
    def from_dict(cls, dikt) -> 'HistoryListINGAMEInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HistoryListINGAME_inner of this HistoryListINGAMEInner.  # noqa: E501
        :rtype: HistoryListINGAMEInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this HistoryListINGAMEInner.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this HistoryListINGAMEInner.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this HistoryListINGAMEInner.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this HistoryListINGAMEInner.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this HistoryListINGAMEInner.

        Timestamp when user created feedback  # noqa: E501

        :return: The timestamp of this HistoryListINGAMEInner.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this HistoryListINGAMEInner.

        Timestamp when user created feedback  # noqa: E501

        :param timestamp: The timestamp of this HistoryListINGAMEInner.
        :type timestamp: datetime
        """

        self._timestamp = timestamp

    @property
    def credits(self) -> int:
        """Gets the credits of this HistoryListINGAMEInner.

        No. of credits.  # noqa: E501

        :return: The credits of this HistoryListINGAMEInner.
        :rtype: int
        """
        return self._credits

    @credits.setter
    def credits(self, credits: int):
        """Sets the credits of this HistoryListINGAMEInner.

        No. of credits.  # noqa: E501

        :param credits: The credits of this HistoryListINGAMEInner.
        :type credits: int
        """

        self._credits = credits

    @property
    def transaction_type(self) -> str:
        """Gets the transaction_type of this HistoryListINGAMEInner.


        :return: The transaction_type of this HistoryListINGAMEInner.
        :rtype: str
        """
        return self._transaction_type

    @transaction_type.setter
    def transaction_type(self, transaction_type: str):
        """Sets the transaction_type of this HistoryListINGAMEInner.


        :param transaction_type: The transaction_type of this HistoryListINGAMEInner.
        :type transaction_type: str
        """

        self._transaction_type = transaction_type
