from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class GetUsernameFromUuid200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None):  # noqa: E501
        """GetUsernameFromUuid200Response - a model defined in OpenAPI

        :param username: The username of this GetUsernameFromUuid200Response.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'username': str
        }

        self.attribute_map = {
            'username': 'username'
        }

        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'GetUsernameFromUuid200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_username_from_uuid_200_response of this GetUsernameFromUuid200Response.  # noqa: E501
        :rtype: GetUsernameFromUuid200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this GetUsernameFromUuid200Response.

        The user's username. Must be at least 5 characters long and contain only letters, numbers, and underscores.  # noqa: E501

        :return: The username of this GetUsernameFromUuid200Response.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this GetUsernameFromUuid200Response.

        The user's username. Must be at least 5 characters long and contain only letters, numbers, and underscores.  # noqa: E501

        :param username: The username of this GetUsernameFromUuid200Response.
        :type username: str
        """
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501
        if username is not None and not re.search(r'^[a-zA-Z0-9_]+$', username):  # noqa: E501
            raise ValueError(r"Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_]+$/`")  # noqa: E501

        self._username = username
