services:
  db:
    image: db_gachaandgames
    container_name: mysql_db_gachaandgames
    build: ./database/
    ports:
      - "127.0.0.1:3306:3306"
    env_file: "database/db.env"
    volumes:
      - mysql_gatchaandgames_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      interval: 1s
      retries: 20

  api:
    image: api_gachaandgames
    container_name: app_api_gachaandgames
    build: ./openapi_server/
    ports:
      - "127.0.0.1:8080:8080"
    env_file: "openapi_server/api.env"
    volumes:
      - ./openapi_server:/usr/src/app/openapi_server
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    tty: true

volumes:
  mysql_gatchaandgames_db: