services:
  api_gateway_public:
    image: nginx:alpine
    container_name: unipi-gatchaandgames-api_gateway_public
    ports:
      - "443:443"
    volumes:
      - ./api_gateway_public/ssl:/etc/nginx/ssl/:ro
      - ./api_gateway_public/api_gateway.conf:/etc/nginx/nginx.conf:ro
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - service_admin
      - service_auction
      - service_auth
      - service_currency
      - service_feedback
      - service_gacha
      - service_inventory
      - service_profile
    #  - service_pvp
    restart: always
    networks:
      - public_gachaandgames_network

  api_gateway_private:
    image: nginx:alpine
    container_name: unipi-gatchaandgames-api_gateway_private
    ports:
      - "444:444"
    volumes:
      - ./api_gateway_private/ssl:/etc/nginx/ssl/:ro
      - ./api_gateway_private/api_gateway.conf:/etc/nginx/nginx.conf:ro
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    depends_on:
      - service_admin
      - service_auction
      - service_auth
      - service_currency
      - service_feedback
      - service_gacha
      - service_inventory
      - service_profile
    #  - service_pvp
    restart: always
    networks:
      - private_gachaandgames_network

  db:
    image: db_gachaandgames
    container_name: unipi-gatchaandgames-database
    build: ./database/
    ports:
      - "3306"
    env_file: "database/db.env"
    volumes:
      - mysql_gatchaandgames_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 10
    restart: always
    networks:
      - private_gachaandgames_network
      - public_gachaandgames_network # to remove

  db_manager:
    image: db_manager_gachaandgames
    build: ./db_manager/
    ports:
      - "8080"
    env_file: ./db_manager/.env
    volumes:
      - ./db_manager:/usr/src/app/
      - ./common/logging.py:/usr/src/app/openapi_server/helpers/logging.py
    depends_on:
      db:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - private_gachaandgames_network
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/db_manager/health_check"]
      start_period: 10s
      interval: 10s
      timeout: 2s
      retries: 5
    deploy:
      replicas: 1

  service_admin:
    image: service_admin
    build: ./services/admin/
    ports:
      - "8080"
    env_file: ./services/admin/.env
    volumes:
      - ./services/admin:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - private_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_auth:
    image: service_auth
    build: ./services/auth/
    ports:
      - "8080"
    env_file: ./services/auth/.env
    volumes:
      - ./services/auth:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      - db_manager
      - logging_loki
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
      - private_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1
  
  service_auction:
    image: service_auction
    build: ./services/auction/
    ports:
      - "8080"
    env_file: ./services/auction/.env
    volumes:
      - ./services/auction:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auction/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1
  
  service_currency:
    image: service_currency
    build: ./services/currency/
    ports:
      - "8080"
    env_file: ./services/currency/.env
    volumes:
      - ./services/currency:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/currency/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_feedback:
    image: service_feedback
    build: ./services/feedback/
    ports:
      - "8080"
    env_file: ./services/feedback/.env
    volumes:
      - ./services/feedback:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/feedback/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_gacha:
    image: service_gacha
    build: ./services/gacha/
    ports:
      - "8080"
    env_file: ./services/gacha/.env
    volumes:
      - ./services/gacha:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/gacha/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_inventory:
    image: service_inventory
    build: ./services/inventory/
    ports:
      - "8080"
    env_file: ./services/inventory/.env
    volumes:
      - ./services/inventory:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/inventory/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_profile:
    image: service_profile
    build: ./services/profile/
    ports:
      - "8080"
    env_file: ./services/profile/.env
    volumes:
      - ./services/profile:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/profile/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  service_pvp:
    image: service_pvp
    build: ./services/pvp/
    ports:
      - "8080"
    env_file: ./services/pvp/.env
    volumes:
      - ./services/pvp:/usr/src/app/
      - ./common/:/usr/src/app/openapi_server/helpers/
    depends_on:
      db_manager:
        condition: service_healthy
    tty: true
    restart: always
    networks:
      - public_gachaandgames_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/pvp/health_check"]
      start_period: 10s
      interval: 1m
      timeout: 2s
      retries: 3
    deploy:
      replicas: 1

  ######### STACK ELK
  logging_loki:
    image: grafana/loki:latest
    container_name: unipi-gatchaandgames-logging_loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    restart: always
    networks:
      - public_gachaandgames_network
      - private_gachaandgames_network

  logging_grafana:
    image: grafana/grafana-oss:10.1.2
    container_name: unipi-gatchaandgames-logging_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./logs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./logs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./logs/grafana/dashboards:/var/lib/grafana/dashboards
      - ./logs/grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file: ./logs/grafana/.env
    depends_on:
      - logging_loki
    restart: always
    networks:
      - private_gachaandgames_network


networks:
  private_gachaandgames_network:
  public_gachaandgames_network:
volumes:
  mysql_gatchaandgames_db:
  grafana_data:
  loki_data: