from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SubmitFeedbackRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content=None):  # noqa: E501
        """SubmitFeedbackRequest - a model defined in OpenAPI

        :param content: The content of this SubmitFeedbackRequest.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'content': str
        }

        self.attribute_map = {
            'content': 'content'
        }

        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'SubmitFeedbackRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The submit_feedback_request of this SubmitFeedbackRequest.  # noqa: E501
        :rtype: SubmitFeedbackRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self) -> str:
        """Gets the content of this SubmitFeedbackRequest.


        :return: The content of this SubmitFeedbackRequest.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this SubmitFeedbackRequest.


        :param content: The content of this SubmitFeedbackRequest.
        :type content: str
        """

        self._content = content
