from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.match_pairing_player1 import MatchPairingPlayer1
from openapi_server import util

from openapi_server.models.match_pairing_player1 import MatchPairingPlayer1  # noqa: E501

class MatchPairing(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, extracted_stat=None, player1=None, player2=None, round_winner=None):  # noqa: E501
        """MatchPairing - a model defined in OpenAPI

        :param extracted_stat: The extracted_stat of this MatchPairing.  # noqa: E501
        :type extracted_stat: str
        :param player1: The player1 of this MatchPairing.  # noqa: E501
        :type player1: MatchPairingPlayer1
        :param player2: The player2 of this MatchPairing.  # noqa: E501
        :type player2: MatchPairingPlayer1
        :param round_winner: The round_winner of this MatchPairing.  # noqa: E501
        :type round_winner: str
        """
        self.openapi_types = {
            'extracted_stat': str,
            'player1': MatchPairingPlayer1,
            'player2': MatchPairingPlayer1,
            'round_winner': str
        }

        self.attribute_map = {
            'extracted_stat': 'extracted_stat',
            'player1': 'player1',
            'player2': 'player2',
            'round_winner': 'round_winner'
        }

        self._extracted_stat = extracted_stat
        self._player1 = player1
        self._player2 = player2
        self._round_winner = round_winner

    @classmethod
    def from_dict(cls, dikt) -> 'MatchPairing':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchPairing of this MatchPairing.  # noqa: E501
        :rtype: MatchPairing
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extracted_stat(self) -> str:
        """Gets the extracted_stat of this MatchPairing.


        :return: The extracted_stat of this MatchPairing.
        :rtype: str
        """
        return self._extracted_stat

    @extracted_stat.setter
    def extracted_stat(self, extracted_stat: str):
        """Sets the extracted_stat of this MatchPairing.


        :param extracted_stat: The extracted_stat of this MatchPairing.
        :type extracted_stat: str
        """
        allowed_values = ["power", "speed", "durability", "precision", "range"]  # noqa: E501
        if extracted_stat not in allowed_values:
            raise ValueError(
                "Invalid value for `extracted_stat` ({0}), must be one of {1}"
                .format(extracted_stat, allowed_values)
            )

        self._extracted_stat = extracted_stat

    @property
    def player1(self) -> MatchPairingPlayer1:
        """Gets the player1 of this MatchPairing.


        :return: The player1 of this MatchPairing.
        :rtype: MatchPairingPlayer1
        """
        return self._player1

    @player1.setter
    def player1(self, player1: MatchPairingPlayer1):
        """Sets the player1 of this MatchPairing.


        :param player1: The player1 of this MatchPairing.
        :type player1: MatchPairingPlayer1
        """

        self._player1 = player1

    @property
    def player2(self) -> MatchPairingPlayer1:
        """Gets the player2 of this MatchPairing.


        :return: The player2 of this MatchPairing.
        :rtype: MatchPairingPlayer1
        """
        return self._player2

    @player2.setter
    def player2(self, player2: MatchPairingPlayer1):
        """Sets the player2 of this MatchPairing.


        :param player2: The player2 of this MatchPairing.
        :type player2: MatchPairingPlayer1
        """

        self._player2 = player2

    @property
    def round_winner(self) -> str:
        """Gets the round_winner of this MatchPairing.


        :return: The round_winner of this MatchPairing.
        :rtype: str
        """
        return self._round_winner

    @round_winner.setter
    def round_winner(self, round_winner: str):
        """Sets the round_winner of this MatchPairing.


        :param round_winner: The round_winner of this MatchPairing.
        :type round_winner: str
        """

        self._round_winner = round_winner
