{
 "title": "Logging",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{level=\"error\"} |= ``"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{level=\"warning\"} |= ``"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{level=\"info\"} |= ``"
    }
   ]
  },
  {
   "title": "General Logs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{level=\"general\"} |= ``"
    }
   ]
  }
 ]
}