from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class IsOpenByItemUuid200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, found=None):  # noqa: E501
        """IsOpenByItemUuid200Response - a model defined in OpenAPI

        :param found: The found of this IsOpenByItemUuid200Response.  # noqa: E501
        :type found: bool
        """
        self.openapi_types = {
            'found': bool
        }

        self.attribute_map = {
            'found': 'found'
        }

        self._found = found

    @classmethod
    def from_dict(cls, dikt) -> 'IsOpenByItemUuid200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The is_open_by_item_uuid_200_response of this IsOpenByItemUuid200Response.  # noqa: E501
        :rtype: IsOpenByItemUuid200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def found(self) -> bool:
        """Gets the found of this IsOpenByItemUuid200Response.


        :return: The found of this IsOpenByItemUuid200Response.
        :rtype: bool
        """
        return self._found

    @found.setter
    def found(self, found: bool):
        """Sets the found of this IsOpenByItemUuid200Response.


        :param found: The found of this IsOpenByItemUuid200Response.
        :type found: bool
        """

        self._found = found
