from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.match_pairing import MatchPairing
from openapi_server import util

from openapi_server.models.match_pairing import MatchPairing  # noqa: E501

class MatchLog(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, rounds=None):  # noqa: E501
        """MatchLog - a model defined in OpenAPI

        :param rounds: The rounds of this MatchLog.  # noqa: E501
        :type rounds: List[MatchPairing]
        """
        self.openapi_types = {
            'rounds': List[MatchPairing]
        }

        self.attribute_map = {
            'rounds': 'rounds'
        }

        self._rounds = rounds

    @classmethod
    def from_dict(cls, dikt) -> 'MatchLog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchLog of this MatchLog.  # noqa: E501
        :rtype: MatchLog
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rounds(self) -> List[MatchPairing]:
        """Gets the rounds of this MatchLog.


        :return: The rounds of this MatchLog.
        :rtype: List[MatchPairing]
        """
        return self._rounds

    @rounds.setter
    def rounds(self, rounds: List[MatchPairing]):
        """Sets the rounds of this MatchLog.


        :param rounds: The rounds of this MatchLog.
        :type rounds: List[MatchPairing]
        """

        self._rounds = rounds
