from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.team import Team
from openapi_server import util

from openapi_server.models.team import Team  # noqa: E501

class PvPRequestTeams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, team1=None, team2=None):  # noqa: E501
        """PvPRequestTeams - a model defined in OpenAPI

        :param team1: The team1 of this PvPRequestTeams.  # noqa: E501
        :type team1: Team
        :param team2: The team2 of this PvPRequestTeams.  # noqa: E501
        :type team2: Team
        """
        self.openapi_types = {
            'team1': Team,
            'team2': Team
        }

        self.attribute_map = {
            'team1': 'team1',
            'team2': 'team2'
        }

        self._team1 = team1
        self._team2 = team2

    @classmethod
    def from_dict(cls, dikt) -> 'PvPRequestTeams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PvPRequest_teams of this PvPRequestTeams.  # noqa: E501
        :rtype: PvPRequestTeams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def team1(self) -> Team:
        """Gets the team1 of this PvPRequestTeams.


        :return: The team1 of this PvPRequestTeams.
        :rtype: Team
        """
        return self._team1

    @team1.setter
    def team1(self, team1: Team):
        """Sets the team1 of this PvPRequestTeams.


        :param team1: The team1 of this PvPRequestTeams.
        :type team1: Team
        """

        self._team1 = team1

    @property
    def team2(self) -> Team:
        """Gets the team2 of this PvPRequestTeams.


        :return: The team2 of this PvPRequestTeams.
        :rtype: Team
        """
        return self._team2

    @team2.setter
    def team2(self, team2: Team):
        """Sets the team2 of this PvPRequestTeams.


        :param team2: The team2 of this PvPRequestTeams.
        :type team2: Team
        """

        self._team2 = team2
