from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class PvPRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pvp_match_uuid=None, sender_id=None, receiver_id=None, winner_id=None, match_log=None, sent_timestamp=None):  # noqa: E501
        """PvPRequest - a model defined in OpenAPI

        :param pvp_match_uuid: The pvp_match_uuid of this PvPRequest.  # noqa: E501
        :type pvp_match_uuid: str
        :param sender_id: The sender_id of this PvPRequest.  # noqa: E501
        :type sender_id: str
        :param receiver_id: The receiver_id of this PvPRequest.  # noqa: E501
        :type receiver_id: str
        :param winner_id: The winner_id of this PvPRequest.  # noqa: E501
        :type winner_id: str
        :param match_log: The match_log of this PvPRequest.  # noqa: E501
        :type match_log: List[str]
        :param sent_timestamp: The sent_timestamp of this PvPRequest.  # noqa: E501
        :type sent_timestamp: datetime
        """
        self.openapi_types = {
            'pvp_match_uuid': str,
            'sender_id': str,
            'receiver_id': str,
            'winner_id': str,
            'match_log': List[str],
            'sent_timestamp': datetime
        }

        self.attribute_map = {
            'pvp_match_uuid': 'pvp_match_uuid',
            'sender_id': 'sender_id',
            'receiver_id': 'receiver_id',
            'winner_id': 'winner_id',
            'match_log': 'match_log',
            'sent_timestamp': 'sent_timestamp'
        }

        self._pvp_match_uuid = pvp_match_uuid
        self._sender_id = sender_id
        self._receiver_id = receiver_id
        self._winner_id = winner_id
        self._match_log = match_log
        self._sent_timestamp = sent_timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'PvPRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PvPRequest of this PvPRequest.  # noqa: E501
        :rtype: PvPRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pvp_match_uuid(self) -> str:
        """Gets the pvp_match_uuid of this PvPRequest.

        UUID of the PvP match.  # noqa: E501

        :return: The pvp_match_uuid of this PvPRequest.
        :rtype: str
        """
        return self._pvp_match_uuid

    @pvp_match_uuid.setter
    def pvp_match_uuid(self, pvp_match_uuid: str):
        """Sets the pvp_match_uuid of this PvPRequest.

        UUID of the PvP match.  # noqa: E501

        :param pvp_match_uuid: The pvp_match_uuid of this PvPRequest.
        :type pvp_match_uuid: str
        """

        self._pvp_match_uuid = pvp_match_uuid

    @property
    def sender_id(self) -> str:
        """Gets the sender_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :return: The sender_id of this PvPRequest.
        :rtype: str
        """
        return self._sender_id

    @sender_id.setter
    def sender_id(self, sender_id: str):
        """Sets the sender_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :param sender_id: The sender_id of this PvPRequest.
        :type sender_id: str
        """

        self._sender_id = sender_id

    @property
    def receiver_id(self) -> str:
        """Gets the receiver_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :return: The receiver_id of this PvPRequest.
        :rtype: str
        """
        return self._receiver_id

    @receiver_id.setter
    def receiver_id(self, receiver_id: str):
        """Sets the receiver_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :param receiver_id: The receiver_id of this PvPRequest.
        :type receiver_id: str
        """

        self._receiver_id = receiver_id

    @property
    def winner_id(self) -> str:
        """Gets the winner_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :return: The winner_id of this PvPRequest.
        :rtype: str
        """
        return self._winner_id

    @winner_id.setter
    def winner_id(self, winner_id: str):
        """Sets the winner_id of this PvPRequest.

        UUID of user.  # noqa: E501

        :param winner_id: The winner_id of this PvPRequest.
        :type winner_id: str
        """

        self._winner_id = winner_id

    @property
    def match_log(self) -> List[str]:
        """Gets the match_log of this PvPRequest.


        :return: The match_log of this PvPRequest.
        :rtype: List[str]
        """
        return self._match_log

    @match_log.setter
    def match_log(self, match_log: List[str]):
        """Sets the match_log of this PvPRequest.


        :param match_log: The match_log of this PvPRequest.
        :type match_log: List[str]
        """

        self._match_log = match_log

    @property
    def sent_timestamp(self) -> datetime:
        """Gets the sent_timestamp of this PvPRequest.

        Request sent timestamp.  # noqa: E501

        :return: The sent_timestamp of this PvPRequest.
        :rtype: datetime
        """
        return self._sent_timestamp

    @sent_timestamp.setter
    def sent_timestamp(self, sent_timestamp: datetime):
        """Sets the sent_timestamp of this PvPRequest.

        Request sent timestamp.  # noqa: E501

        :param sent_timestamp: The sent_timestamp of this PvPRequest.
        :type sent_timestamp: datetime
        """

        self._sent_timestamp = sent_timestamp
