from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.history_list_ingame_inner import HistoryListINGAMEInner
from openapi_server import util

from openapi_server.models.history_list_ingame_inner import HistoryListINGAMEInner  # noqa: E501

class HistoryListINGAME(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """HistoryListINGAME - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'HistoryListINGAME':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HistoryListINGAME of this HistoryListINGAME.  # noqa: E501
        :rtype: HistoryListINGAME
        """
        return util.deserialize_model(dikt, cls)
