from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GachaRarity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COMMON = 'common'
    RARE = 'rare'
    EPIC = 'epic'
    LEGENDARY = 'legendary'
    def __init__(self):  # noqa: E501
        """GachaRarity - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GachaRarity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GachaRarity of this GachaRarity.  # noqa: E501
        :rtype: GachaRarity
        """
        return util.deserialize_model(dikt, cls)
