from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.roles import Roles
from openapi_server import util

from openapi_server.models.roles import Roles  # noqa: E501

class GetRoleByUuid200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, role=None):  # noqa: E501
        """GetRoleByUuid200Response - a model defined in OpenAPI

        :param role: The role of this GetRoleByUuid200Response.  # noqa: E501
        :type role: Roles
        """
        self.openapi_types = {
            'role': Roles
        }

        self.attribute_map = {
            'role': 'role'
        }

        self._role = role

    @classmethod
    def from_dict(cls, dikt) -> 'GetRoleByUuid200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_role_by_uuid_200_response of this GetRoleByUuid200Response.  # noqa: E501
        :rtype: GetRoleByUuid200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def role(self) -> Roles:
        """Gets the role of this GetRoleByUuid200Response.


        :return: The role of this GetRoleByUuid200Response.
        :rtype: Roles
        """
        return self._role

    @role.setter
    def role(self, role: Roles):
        """Sets the role of this GetRoleByUuid200Response.


        :param role: The role of this GetRoleByUuid200Response.
        :type role: Roles
        """

        self._role = role
