from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class IntrospectRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, access_token=None):  # noqa: E501
        """IntrospectRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this IntrospectRequest.  # noqa: E501
        :type user_uuid: str
        :param access_token: The access_token of this IntrospectRequest.  # noqa: E501
        :type access_token: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'access_token': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'access_token': 'AccessToken'
        }

        self._user_uuid = user_uuid
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'IntrospectRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The introspect_request of this IntrospectRequest.  # noqa: E501
        :rtype: IntrospectRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this IntrospectRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this IntrospectRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this IntrospectRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this IntrospectRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def access_token(self) -> str:
        """Gets the access_token of this IntrospectRequest.


        :return: The access_token of this IntrospectRequest.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this IntrospectRequest.


        :param access_token: The access_token of this IntrospectRequest.
        :type access_token: str
        """

        self._access_token = access_token
