from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class IntrospectRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_token=None, audience_required=None):  # noqa: E501
        """IntrospectRequest - a model defined in OpenAPI

        :param access_token: The access_token of this IntrospectRequest.  # noqa: E501
        :type access_token: str
        :param audience_required: The audience_required of this IntrospectRequest.  # noqa: E501
        :type audience_required: str
        """
        self.openapi_types = {
            'access_token': str,
            'audience_required': str
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'audience_required': 'audience_required'
        }

        self._access_token = access_token
        self._audience_required = audience_required

    @classmethod
    def from_dict(cls, dikt) -> 'IntrospectRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The introspect_request of this IntrospectRequest.  # noqa: E501
        :rtype: IntrospectRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this IntrospectRequest.


        :return: The access_token of this IntrospectRequest.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this IntrospectRequest.


        :param access_token: The access_token of this IntrospectRequest.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def audience_required(self) -> str:
        """Gets the audience_required of this IntrospectRequest.


        :return: The audience_required of this IntrospectRequest.
        :rtype: str
        """
        return self._audience_required

    @audience_required.setter
    def audience_required(self, audience_required: str):
        """Sets the audience_required of this IntrospectRequest.


        :param audience_required: The audience_required of this IntrospectRequest.
        :type audience_required: str
        """

        self._audience_required = audience_required
