from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BanUserProfileRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None):  # noqa: E501
        """BanUserProfileRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this BanUserProfileRequest.  # noqa: E501
        :type user_uuid: str
        """
        self.openapi_types = {
            'user_uuid': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid'
        }

        self._user_uuid = user_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'BanUserProfileRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ban_user_profile_request of this BanUserProfileRequest.  # noqa: E501
        :rtype: BanUserProfileRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this BanUserProfileRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this BanUserProfileRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this BanUserProfileRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this BanUserProfileRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid
