from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class CompleteAuctionSaleRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item_uuid=None, current_bid=None, user_uuid=None):  # noqa: E501
        """CompleteAuctionSaleRequest - a model defined in OpenAPI

        :param item_uuid: The item_uuid of this CompleteAuctionSaleRequest.  # noqa: E501
        :type item_uuid: str
        :param current_bid: The current_bid of this CompleteAuctionSaleRequest.  # noqa: E501
        :type current_bid: int
        :param user_uuid: The user_uuid of this CompleteAuctionSaleRequest.  # noqa: E501
        :type user_uuid: str
        """
        self.openapi_types = {
            'item_uuid': str,
            'current_bid': int,
            'user_uuid': str
        }

        self.attribute_map = {
            'item_uuid': 'item_uuid',
            'current_bid': 'current_bid',
            'user_uuid': 'user_uuid'
        }

        self._item_uuid = item_uuid
        self._current_bid = current_bid
        self._user_uuid = user_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'CompleteAuctionSaleRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The complete_auction_sale_request of this CompleteAuctionSaleRequest.  # noqa: E501
        :rtype: CompleteAuctionSaleRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_uuid(self) -> str:
        """Gets the item_uuid of this CompleteAuctionSaleRequest.

        UUID of single item.  # noqa: E501

        :return: The item_uuid of this CompleteAuctionSaleRequest.
        :rtype: str
        """
        return self._item_uuid

    @item_uuid.setter
    def item_uuid(self, item_uuid: str):
        """Sets the item_uuid of this CompleteAuctionSaleRequest.

        UUID of single item.  # noqa: E501

        :param item_uuid: The item_uuid of this CompleteAuctionSaleRequest.
        :type item_uuid: str
        """

        self._item_uuid = item_uuid

    @property
    def current_bid(self) -> int:
        """Gets the current_bid of this CompleteAuctionSaleRequest.


        :return: The current_bid of this CompleteAuctionSaleRequest.
        :rtype: int
        """
        return self._current_bid

    @current_bid.setter
    def current_bid(self, current_bid: int):
        """Sets the current_bid of this CompleteAuctionSaleRequest.


        :param current_bid: The current_bid of this CompleteAuctionSaleRequest.
        :type current_bid: int
        """

        self._current_bid = current_bid

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this CompleteAuctionSaleRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this CompleteAuctionSaleRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this CompleteAuctionSaleRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this CompleteAuctionSaleRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid
