from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class EditUserInfoRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, username=None, email=None):  # noqa: E501
        """EditUserInfoRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this EditUserInfoRequest.  # noqa: E501
        :type user_uuid: str
        :param username: The username of this EditUserInfoRequest.  # noqa: E501
        :type username: str
        :param email: The email of this EditUserInfoRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'username': str,
            'email': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'username': 'username',
            'email': 'email'
        }

        self._user_uuid = user_uuid
        self._username = username
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'EditUserInfoRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The edit_user_info_request of this EditUserInfoRequest.  # noqa: E501
        :rtype: EditUserInfoRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this EditUserInfoRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this EditUserInfoRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this EditUserInfoRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this EditUserInfoRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def username(self) -> str:
        """Gets the username of this EditUserInfoRequest.

        The username of the user  # noqa: E501

        :return: The username of this EditUserInfoRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this EditUserInfoRequest.

        The username of the user  # noqa: E501

        :param username: The username of this EditUserInfoRequest.
        :type username: str
        """
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501
        if username is not None and not re.search(r'^[a-zA-Z0-9_]+$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_]+$/`")  # noqa: E501

        self._username = username

    @property
    def email(self) -> str:
        """Gets the email of this EditUserInfoRequest.

        The user's email.  # noqa: E501

        :return: The email of this EditUserInfoRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this EditUserInfoRequest.

        The user's email.  # noqa: E501

        :param email: The email of this EditUserInfoRequest.
        :type email: str
        """

        self._email = email
