from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class FeedbackWithUsername(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, user_uuid=None, username=None, content=None, timestamp=None):  # noqa: E501
        """FeedbackWithUsername - a model defined in OpenAPI

        :param id: The id of this FeedbackWithUsername.  # noqa: E501
        :type id: int
        :param user_uuid: The user_uuid of this FeedbackWithUsername.  # noqa: E501
        :type user_uuid: str
        :param username: The username of this FeedbackWithUsername.  # noqa: E501
        :type username: str
        :param content: The content of this FeedbackWithUsername.  # noqa: E501
        :type content: str
        :param timestamp: The timestamp of this FeedbackWithUsername.  # noqa: E501
        :type timestamp: datetime
        """
        self.openapi_types = {
            'id': int,
            'user_uuid': str,
            'username': str,
            'content': str,
            'timestamp': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'user_uuid': 'user_uuid',
            'username': 'username',
            'content': 'content',
            'timestamp': 'timestamp'
        }

        self._id = id
        self._user_uuid = user_uuid
        self._username = username
        self._content = content
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt) -> 'FeedbackWithUsername':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FeedbackWithUsername of this FeedbackWithUsername.  # noqa: E501
        :rtype: FeedbackWithUsername
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this FeedbackWithUsername.

        Id of feedback.  # noqa: E501

        :return: The id of this FeedbackWithUsername.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this FeedbackWithUsername.

        Id of feedback.  # noqa: E501

        :param id: The id of this FeedbackWithUsername.
        :type id: int
        """

        self._id = id

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this FeedbackWithUsername.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this FeedbackWithUsername.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this FeedbackWithUsername.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this FeedbackWithUsername.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def username(self) -> str:
        """Gets the username of this FeedbackWithUsername.

        The username of the user  # noqa: E501

        :return: The username of this FeedbackWithUsername.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this FeedbackWithUsername.

        The username of the user  # noqa: E501

        :param username: The username of this FeedbackWithUsername.
        :type username: str
        """
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501
        if username is not None and not re.search(r'^[a-zA-Z0-9_]+$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_]+$/`")  # noqa: E501

        self._username = username

    @property
    def content(self) -> str:
        """Gets the content of this FeedbackWithUsername.

        Actual feedback content.  # noqa: E501

        :return: The content of this FeedbackWithUsername.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this FeedbackWithUsername.

        Actual feedback content.  # noqa: E501

        :param content: The content of this FeedbackWithUsername.
        :type content: str
        """

        self._content = content

    @property
    def timestamp(self) -> datetime:
        """Gets the timestamp of this FeedbackWithUsername.

        Timestamp when user created feedback  # noqa: E501

        :return: The timestamp of this FeedbackWithUsername.
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: datetime):
        """Sets the timestamp of this FeedbackWithUsername.

        Timestamp when user created feedback  # noqa: E501

        :param timestamp: The timestamp of this FeedbackWithUsername.
        :type timestamp: datetime
        """

        self._timestamp = timestamp
