from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetInventoryItemRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, inventory_item_id=None):  # noqa: E501
        """GetInventoryItemRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this GetInventoryItemRequest.  # noqa: E501
        :type user_uuid: str
        :param inventory_item_id: The inventory_item_id of this GetInventoryItemRequest.  # noqa: E501
        :type inventory_item_id: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'inventory_item_id': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'inventory_item_id': 'inventory_item_id'
        }

        self._user_uuid = user_uuid
        self._inventory_item_id = inventory_item_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetInventoryItemRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_inventory_item_request of this GetInventoryItemRequest.  # noqa: E501
        :rtype: GetInventoryItemRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this GetInventoryItemRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this GetInventoryItemRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this GetInventoryItemRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this GetInventoryItemRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def inventory_item_id(self) -> str:
        """Gets the inventory_item_id of this GetInventoryItemRequest.

        UUID of single item.  # noqa: E501

        :return: The inventory_item_id of this GetInventoryItemRequest.
        :rtype: str
        """
        return self._inventory_item_id

    @inventory_item_id.setter
    def inventory_item_id(self, inventory_item_id: str):
        """Sets the inventory_item_id of this GetInventoryItemRequest.

        UUID of single item.  # noqa: E501

        :param inventory_item_id: The inventory_item_id of this GetInventoryItemRequest.
        :type inventory_item_id: str
        """

        self._inventory_item_id = inventory_item_id
