from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.bundle import Bundle
from openapi_server import util

from openapi_server.models.bundle import Bundle  # noqa: E501

class GetBundleInfo200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bundle=None):  # noqa: E501
        """GetBundleInfo200Response - a model defined in OpenAPI

        :param bundle: The bundle of this GetBundleInfo200Response.  # noqa: E501
        :type bundle: Bundle
        """
        self.openapi_types = {
            'bundle': Bundle
        }

        self.attribute_map = {
            'bundle': 'bundle'
        }

        self._bundle = bundle

    @classmethod
    def from_dict(cls, dikt) -> 'GetBundleInfo200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_bundle_info_200_response of this GetBundleInfo200Response.  # noqa: E501
        :rtype: GetBundleInfo200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bundle(self) -> Bundle:
        """Gets the bundle of this GetBundleInfo200Response.


        :return: The bundle of this GetBundleInfo200Response.
        :rtype: Bundle
        """
        return self._bundle

    @bundle.setter
    def bundle(self, bundle: Bundle):
        """Sets the bundle of this GetBundleInfo200Response.


        :param bundle: The bundle of this GetBundleInfo200Response.
        :type bundle: Bundle
        """

        self._bundle = bundle
