from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetFeedbackInfoRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, feedback_id=None):  # noqa: E501
        """GetFeedbackInfoRequest - a model defined in OpenAPI

        :param feedback_id: The feedback_id of this GetFeedbackInfoRequest.  # noqa: E501
        :type feedback_id: int
        """
        self.openapi_types = {
            'feedback_id': int
        }

        self.attribute_map = {
            'feedback_id': 'feedback_id'
        }

        self._feedback_id = feedback_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetFeedbackInfoRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_feedback_info_request of this GetFeedbackInfoRequest.  # noqa: E501
        :rtype: GetFeedbackInfoRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def feedback_id(self) -> int:
        """Gets the feedback_id of this GetFeedbackInfoRequest.

        Id of feedback.  # noqa: E501

        :return: The feedback_id of this GetFeedbackInfoRequest.
        :rtype: int
        """
        return self._feedback_id

    @feedback_id.setter
    def feedback_id(self, feedback_id: int):
        """Sets the feedback_id of this GetFeedbackInfoRequest.

        Id of feedback.  # noqa: E501

        :param feedback_id: The feedback_id of this GetFeedbackInfoRequest.
        :type feedback_id: int
        """

        self._feedback_id = feedback_id
