from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetAuctionStatusRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None):  # noqa: E501
        """GetAuctionStatusRequest - a model defined in OpenAPI

        :param uuid: The uuid of this GetAuctionStatusRequest.  # noqa: E501
        :type uuid: str
        """
        self.openapi_types = {
            'uuid': str
        }

        self.attribute_map = {
            'uuid': 'uuid'
        }

        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'GetAuctionStatusRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_auction_status_request of this GetAuctionStatusRequest.  # noqa: E501
        :rtype: GetAuctionStatusRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this GetAuctionStatusRequest.

        UUID of the auction.  # noqa: E501

        :return: The uuid of this GetAuctionStatusRequest.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this GetAuctionStatusRequest.

        UUID of the auction.  # noqa: E501

        :param uuid: The uuid of this GetAuctionStatusRequest.
        :type uuid: str
        """

        self._uuid = uuid
