from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetBundleInfoRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bundle_id=None):  # noqa: E501
        """GetBundleInfoRequest - a model defined in OpenAPI

        :param bundle_id: The bundle_id of this GetBundleInfoRequest.  # noqa: E501
        :type bundle_id: str
        """
        self.openapi_types = {
            'bundle_id': str
        }

        self.attribute_map = {
            'bundle_id': 'bundle_id'
        }

        self._bundle_id = bundle_id

    @classmethod
    def from_dict(cls, dikt) -> 'GetBundleInfoRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_bundle_info_request of this GetBundleInfoRequest.  # noqa: E501
        :rtype: GetBundleInfoRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bundle_id(self) -> str:
        """Gets the bundle_id of this GetBundleInfoRequest.

        Codename of the bundle to retrieve.  # noqa: E501

        :return: The bundle_id of this GetBundleInfoRequest.
        :rtype: str
        """
        return self._bundle_id

    @bundle_id.setter
    def bundle_id(self, bundle_id: str):
        """Sets the bundle_id of this GetBundleInfoRequest.

        Codename of the bundle to retrieve.  # noqa: E501

        :param bundle_id: The bundle_id of this GetBundleInfoRequest.
        :type bundle_id: str
        """

        self._bundle_id = bundle_id
