from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetGachaStatRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, player1_stand=None, player2_stand=None):  # noqa: E501
        """GetGachaStatRequest - a model defined in OpenAPI

        :param player1_stand: The player1_stand of this GetGachaStatRequest.  # noqa: E501
        :type player1_stand: str
        :param player2_stand: The player2_stand of this GetGachaStatRequest.  # noqa: E501
        :type player2_stand: str
        """
        self.openapi_types = {
            'player1_stand': str,
            'player2_stand': str
        }

        self.attribute_map = {
            'player1_stand': 'player1_stand',
            'player2_stand': 'player2_stand'
        }

        self._player1_stand = player1_stand
        self._player2_stand = player2_stand

    @classmethod
    def from_dict(cls, dikt) -> 'GetGachaStatRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_gacha_stat_request of this GetGachaStatRequest.  # noqa: E501
        :rtype: GetGachaStatRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def player1_stand(self) -> str:
        """Gets the player1_stand of this GetGachaStatRequest.

        UUID of single item.  # noqa: E501

        :return: The player1_stand of this GetGachaStatRequest.
        :rtype: str
        """
        return self._player1_stand

    @player1_stand.setter
    def player1_stand(self, player1_stand: str):
        """Sets the player1_stand of this GetGachaStatRequest.

        UUID of single item.  # noqa: E501

        :param player1_stand: The player1_stand of this GetGachaStatRequest.
        :type player1_stand: str
        """

        self._player1_stand = player1_stand

    @property
    def player2_stand(self) -> str:
        """Gets the player2_stand of this GetGachaStatRequest.

        UUID of single item.  # noqa: E501

        :return: The player2_stand of this GetGachaStatRequest.
        :rtype: str
        """
        return self._player2_stand

    @player2_stand.setter
    def player2_stand(self, player2_stand: str):
        """Sets the player2_stand of this GetGachaStatRequest.

        UUID of single item.  # noqa: E501

        :param player2_stand: The player2_stand of this GetGachaStatRequest.
        :type player2_stand: str
        """

        self._player2_stand = player2_stand
