from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.auction import Auction
from openapi_server import util

from openapi_server.models.auction import Auction  # noqa: E501

class GetAuctionStatus200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, auction=None):  # noqa: E501
        """GetAuctionStatus200Response - a model defined in OpenAPI

        :param auction: The auction of this GetAuctionStatus200Response.  # noqa: E501
        :type auction: Auction
        """
        self.openapi_types = {
            'auction': Auction
        }

        self.attribute_map = {
            'auction': 'auction'
        }

        self._auction = auction

    @classmethod
    def from_dict(cls, dikt) -> 'GetAuctionStatus200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_auction_status_200_response of this GetAuctionStatus200Response.  # noqa: E501
        :rtype: GetAuctionStatus200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def auction(self) -> Auction:
        """Gets the auction of this GetAuctionStatus200Response.


        :return: The auction of this GetAuctionStatus200Response.
        :rtype: Auction
        """
        return self._auction

    @auction.setter
    def auction(self, auction: Auction):
        """Sets the auction of this GetAuctionStatus200Response.


        :param auction: The auction of this GetAuctionStatus200Response.
        :type auction: Auction
        """

        self._auction = auction
