from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetItemWithOwnerRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, item_uuid=None):  # noqa: E501
        """GetItemWithOwnerRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this GetItemWithOwnerRequest.  # noqa: E501
        :type user_uuid: str
        :param item_uuid: The item_uuid of this GetItemWithOwnerRequest.  # noqa: E501
        :type item_uuid: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'item_uuid': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'item_uuid': 'item_uuid'
        }

        self._user_uuid = user_uuid
        self._item_uuid = item_uuid

    @classmethod
    def from_dict(cls, dikt) -> 'GetItemWithOwnerRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_item_with_owner_request of this GetItemWithOwnerRequest.  # noqa: E501
        :rtype: GetItemWithOwnerRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this GetItemWithOwnerRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this GetItemWithOwnerRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this GetItemWithOwnerRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this GetItemWithOwnerRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def item_uuid(self) -> str:
        """Gets the item_uuid of this GetItemWithOwnerRequest.

        UUID of single item.  # noqa: E501

        :return: The item_uuid of this GetItemWithOwnerRequest.
        :rtype: str
        """
        return self._item_uuid

    @item_uuid.setter
    def item_uuid(self, item_uuid: str):
        """Sets the item_uuid of this GetItemWithOwnerRequest.

        UUID of single item.  # noqa: E501

        :param item_uuid: The item_uuid of this GetItemWithOwnerRequest.
        :type item_uuid: str
        """

        self._item_uuid = item_uuid
