from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class Login200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, uuid_hex=None, email=None, username=None, role=None, password=None):  # noqa: E501
        """Login200Response - a model defined in OpenAPI

        :param uuid: The uuid of this Login200Response.  # noqa: E501
        :type uuid: str
        :param uuid_hex: The uuid_hex of this Login200Response.  # noqa: E501
        :type uuid_hex: str
        :param email: The email of this Login200Response.  # noqa: E501
        :type email: str
        :param username: The username of this Login200Response.  # noqa: E501
        :type username: str
        :param role: The role of this Login200Response.  # noqa: E501
        :type role: str
        :param password: The password of this Login200Response.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'uuid': str,
            'uuid_hex': str,
            'email': str,
            'username': str,
            'role': str,
            'password': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'uuid_hex': 'uuid_hex',
            'email': 'email',
            'username': 'username',
            'role': 'role',
            'password': 'password'
        }

        self._uuid = uuid
        self._uuid_hex = uuid_hex
        self._email = email
        self._username = username
        self._role = role
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'Login200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The login_200_response of this Login200Response.  # noqa: E501
        :rtype: Login200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this Login200Response.

        UUID of user.  # noqa: E501

        :return: The uuid of this Login200Response.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this Login200Response.

        UUID of user.  # noqa: E501

        :param uuid: The uuid of this Login200Response.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def uuid_hex(self) -> str:
        """Gets the uuid_hex of this Login200Response.

        UUID of user in hex format.  # noqa: E501

        :return: The uuid_hex of this Login200Response.
        :rtype: str
        """
        return self._uuid_hex

    @uuid_hex.setter
    def uuid_hex(self, uuid_hex: str):
        """Sets the uuid_hex of this Login200Response.

        UUID of user in hex format.  # noqa: E501

        :param uuid_hex: The uuid_hex of this Login200Response.
        :type uuid_hex: str
        """

        self._uuid_hex = uuid_hex

    @property
    def email(self) -> str:
        """Gets the email of this Login200Response.

        The user's email.  # noqa: E501

        :return: The email of this Login200Response.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Login200Response.

        The user's email.  # noqa: E501

        :param email: The email of this Login200Response.
        :type email: str
        """

        self._email = email

    @property
    def username(self) -> str:
        """Gets the username of this Login200Response.

        The username of the user  # noqa: E501

        :return: The username of this Login200Response.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Login200Response.

        The username of the user  # noqa: E501

        :param username: The username of this Login200Response.
        :type username: str
        """
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501
        if username is not None and not re.search(r'^[a-zA-Z0-9_]+$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_]+$/`")  # noqa: E501

        self._username = username

    @property
    def role(self) -> str:
        """Gets the role of this Login200Response.

        User's role in the system.  # noqa: E501

        :return: The role of this Login200Response.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role: str):
        """Sets the role of this Login200Response.

        User's role in the system.  # noqa: E501

        :param role: The role of this Login200Response.
        :type role: str
        """

        self._role = role

    @property
    def password(self) -> str:
        """Gets the password of this Login200Response.

        The user's password must be at least 8 characters and can accept all characters.  # noqa: E501

        :return: The password of this Login200Response.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this Login200Response.

        The user's password must be at least 8 characters and can accept all characters.  # noqa: E501

        :param password: The password of this Login200Response.
        :type password: str
        """
        if password is not None and len(password) < 8:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `8`")  # noqa: E501

        self._password = password
