from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class MatchRequestsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pvp_match_uuid=None, _from=None):  # noqa: E501
        """MatchRequestsInner - a model defined in OpenAPI

        :param pvp_match_uuid: The pvp_match_uuid of this MatchRequestsInner.  # noqa: E501
        :type pvp_match_uuid: str
        :param _from: The _from of this MatchRequestsInner.  # noqa: E501
        :type _from: str
        """
        self.openapi_types = {
            'pvp_match_uuid': str,
            '_from': str
        }

        self.attribute_map = {
            'pvp_match_uuid': 'pvp_match_uuid',
            '_from': 'from'
        }

        self._pvp_match_uuid = pvp_match_uuid
        self.__from = _from

    @classmethod
    def from_dict(cls, dikt) -> 'MatchRequestsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MatchRequests_inner of this MatchRequestsInner.  # noqa: E501
        :rtype: MatchRequestsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pvp_match_uuid(self) -> str:
        """Gets the pvp_match_uuid of this MatchRequestsInner.

        UUID of the PvP match.  # noqa: E501

        :return: The pvp_match_uuid of this MatchRequestsInner.
        :rtype: str
        """
        return self._pvp_match_uuid

    @pvp_match_uuid.setter
    def pvp_match_uuid(self, pvp_match_uuid: str):
        """Sets the pvp_match_uuid of this MatchRequestsInner.

        UUID of the PvP match.  # noqa: E501

        :param pvp_match_uuid: The pvp_match_uuid of this MatchRequestsInner.
        :type pvp_match_uuid: str
        """

        self._pvp_match_uuid = pvp_match_uuid

    @property
    def _from(self) -> str:
        """Gets the _from of this MatchRequestsInner.

        UUID of user.  # noqa: E501

        :return: The _from of this MatchRequestsInner.
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from: str):
        """Sets the _from of this MatchRequestsInner.

        UUID of user.  # noqa: E501

        :param _from: The _from of this MatchRequestsInner.
        :type _from: str
        """

        self.__from = _from
