from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.match_log import MatchLog
from openapi_server.models.pv_p_request_full_teams import PvPRequestFullTeams
from openapi_server import util

from openapi_server.models.match_log import MatchLog  # noqa: E501
from openapi_server.models.pv_p_request_full_teams import PvPRequestFullTeams  # noqa: E501

class PvPRequestFull(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pvp_match_uuid=None, sender_id=None, receiver_id=None, teams=None, winner=None, match_log=None):  # noqa: E501
        """PvPRequestFull - a model defined in OpenAPI

        :param pvp_match_uuid: The pvp_match_uuid of this PvPRequestFull.  # noqa: E501
        :type pvp_match_uuid: str
        :param sender_id: The sender_id of this PvPRequestFull.  # noqa: E501
        :type sender_id: str
        :param receiver_id: The receiver_id of this PvPRequestFull.  # noqa: E501
        :type receiver_id: str
        :param teams: The teams of this PvPRequestFull.  # noqa: E501
        :type teams: PvPRequestFullTeams
        :param winner: The winner of this PvPRequestFull.  # noqa: E501
        :type winner: bool
        :param match_log: The match_log of this PvPRequestFull.  # noqa: E501
        :type match_log: MatchLog
        """
        self.openapi_types = {
            'pvp_match_uuid': str,
            'sender_id': str,
            'receiver_id': str,
            'teams': PvPRequestFullTeams,
            'winner': bool,
            'match_log': MatchLog
        }

        self.attribute_map = {
            'pvp_match_uuid': 'pvp_match_uuid',
            'sender_id': 'sender_id',
            'receiver_id': 'receiver_id',
            'teams': 'teams',
            'winner': 'winner',
            'match_log': 'match_log'
        }

        self._pvp_match_uuid = pvp_match_uuid
        self._sender_id = sender_id
        self._receiver_id = receiver_id
        self._teams = teams
        self._winner = winner
        self._match_log = match_log

    @classmethod
    def from_dict(cls, dikt) -> 'PvPRequestFull':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PvPRequestFull of this PvPRequestFull.  # noqa: E501
        :rtype: PvPRequestFull
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pvp_match_uuid(self) -> str:
        """Gets the pvp_match_uuid of this PvPRequestFull.

        UUID of the PvP match.  # noqa: E501

        :return: The pvp_match_uuid of this PvPRequestFull.
        :rtype: str
        """
        return self._pvp_match_uuid

    @pvp_match_uuid.setter
    def pvp_match_uuid(self, pvp_match_uuid: str):
        """Sets the pvp_match_uuid of this PvPRequestFull.

        UUID of the PvP match.  # noqa: E501

        :param pvp_match_uuid: The pvp_match_uuid of this PvPRequestFull.
        :type pvp_match_uuid: str
        """

        self._pvp_match_uuid = pvp_match_uuid

    @property
    def sender_id(self) -> str:
        """Gets the sender_id of this PvPRequestFull.

        UUID of user.  # noqa: E501

        :return: The sender_id of this PvPRequestFull.
        :rtype: str
        """
        return self._sender_id

    @sender_id.setter
    def sender_id(self, sender_id: str):
        """Sets the sender_id of this PvPRequestFull.

        UUID of user.  # noqa: E501

        :param sender_id: The sender_id of this PvPRequestFull.
        :type sender_id: str
        """

        self._sender_id = sender_id

    @property
    def receiver_id(self) -> str:
        """Gets the receiver_id of this PvPRequestFull.

        UUID of user.  # noqa: E501

        :return: The receiver_id of this PvPRequestFull.
        :rtype: str
        """
        return self._receiver_id

    @receiver_id.setter
    def receiver_id(self, receiver_id: str):
        """Sets the receiver_id of this PvPRequestFull.

        UUID of user.  # noqa: E501

        :param receiver_id: The receiver_id of this PvPRequestFull.
        :type receiver_id: str
        """

        self._receiver_id = receiver_id

    @property
    def teams(self) -> PvPRequestFullTeams:
        """Gets the teams of this PvPRequestFull.


        :return: The teams of this PvPRequestFull.
        :rtype: PvPRequestFullTeams
        """
        return self._teams

    @teams.setter
    def teams(self, teams: PvPRequestFullTeams):
        """Sets the teams of this PvPRequestFull.


        :param teams: The teams of this PvPRequestFull.
        :type teams: PvPRequestFullTeams
        """

        self._teams = teams

    @property
    def winner(self) -> bool:
        """Gets the winner of this PvPRequestFull.

        True if winner is player1, False if winner is player2, empty if there is no winner yet  # noqa: E501

        :return: The winner of this PvPRequestFull.
        :rtype: bool
        """
        return self._winner

    @winner.setter
    def winner(self, winner: bool):
        """Sets the winner of this PvPRequestFull.

        True if winner is player1, False if winner is player2, empty if there is no winner yet  # noqa: E501

        :param winner: The winner of this PvPRequestFull.
        :type winner: bool
        """

        self._winner = winner

    @property
    def match_log(self) -> MatchLog:
        """Gets the match_log of this PvPRequestFull.


        :return: The match_log of this PvPRequestFull.
        :rtype: MatchLog
        """
        return self._match_log

    @match_log.setter
    def match_log(self, match_log: MatchLog):
        """Sets the match_log of this PvPRequestFull.


        :param match_log: The match_log of this PvPRequestFull.
        :type match_log: MatchLog
        """

        self._match_log = match_log
