from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
import re
from openapi_server import util

import re  # noqa: E501

class RegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, email=None, password=None, username=None):  # noqa: E501
        """RegisterRequest - a model defined in OpenAPI

        :param uuid: The uuid of this RegisterRequest.  # noqa: E501
        :type uuid: str
        :param email: The email of this RegisterRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterRequest.  # noqa: E501
        :type password: str
        :param username: The username of this RegisterRequest.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'uuid': str,
            'email': str,
            'password': str,
            'username': str
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'email': 'email',
            'password': 'password',
            'username': 'username'
        }

        self._uuid = uuid
        self._email = email
        self._password = password
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The register_request of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this RegisterRequest.

        UUID of user.  # noqa: E501

        :return: The uuid of this RegisterRequest.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this RegisterRequest.

        UUID of user.  # noqa: E501

        :param uuid: The uuid of this RegisterRequest.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def email(self) -> str:
        """Gets the email of this RegisterRequest.

        The user's email.  # noqa: E501

        :return: The email of this RegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterRequest.

        The user's email.  # noqa: E501

        :param email: The email of this RegisterRequest.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this RegisterRequest.

        User's password.  # noqa: E501

        :return: The password of this RegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterRequest.

        User's password.  # noqa: E501

        :param password: The password of this RegisterRequest.
        :type password: str
        """

        self._password = password

    @property
    def username(self) -> str:
        """Gets the username of this RegisterRequest.

        The username of the user  # noqa: E501

        :return: The username of this RegisterRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this RegisterRequest.

        The username of the user  # noqa: E501

        :param username: The username of this RegisterRequest.
        :type username: str
        """
        if username is not None and len(username) < 5:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `5`")  # noqa: E501
        if username is not None and not re.search(r'^[a-zA-Z0-9_]+$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_]+$/`")  # noqa: E501

        self._username = username
