from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class SubmitFeedbackRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_uuid=None, string=None):  # noqa: E501
        """SubmitFeedbackRequest - a model defined in OpenAPI

        :param user_uuid: The user_uuid of this SubmitFeedbackRequest.  # noqa: E501
        :type user_uuid: str
        :param string: The string of this SubmitFeedbackRequest.  # noqa: E501
        :type string: str
        """
        self.openapi_types = {
            'user_uuid': str,
            'string': str
        }

        self.attribute_map = {
            'user_uuid': 'user_uuid',
            'string': 'string'
        }

        self._user_uuid = user_uuid
        self._string = string

    @classmethod
    def from_dict(cls, dikt) -> 'SubmitFeedbackRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The submit_feedback_request of this SubmitFeedbackRequest.  # noqa: E501
        :rtype: SubmitFeedbackRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_uuid(self) -> str:
        """Gets the user_uuid of this SubmitFeedbackRequest.

        UUID of user.  # noqa: E501

        :return: The user_uuid of this SubmitFeedbackRequest.
        :rtype: str
        """
        return self._user_uuid

    @user_uuid.setter
    def user_uuid(self, user_uuid: str):
        """Sets the user_uuid of this SubmitFeedbackRequest.

        UUID of user.  # noqa: E501

        :param user_uuid: The user_uuid of this SubmitFeedbackRequest.
        :type user_uuid: str
        """

        self._user_uuid = user_uuid

    @property
    def string(self) -> str:
        """Gets the string of this SubmitFeedbackRequest.

        The feedback content provided by the user.  # noqa: E501

        :return: The string of this SubmitFeedbackRequest.
        :rtype: str
        """
        return self._string

    @string.setter
    def string(self, string: str):
        """Sets the string of this SubmitFeedbackRequest.

        The feedback content provided by the user.  # noqa: E501

        :param string: The string of this SubmitFeedbackRequest.
        :type string: str
        """

        self._string = string
