from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GetUuidFromUsername200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None):  # noqa: E501
        """GetUuidFromUsername200Response - a model defined in OpenAPI

        :param username: The username of this GetUuidFromUsername200Response.  # noqa: E501
        :type username: str
        """
        self.openapi_types = {
            'username': str
        }

        self.attribute_map = {
            'username': 'username'
        }

        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'GetUuidFromUsername200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_uuid_from_username_200_response of this GetUuidFromUsername200Response.  # noqa: E501
        :rtype: GetUuidFromUsername200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this GetUuidFromUsername200Response.

        UUID of user.  # noqa: E501

        :return: The username of this GetUuidFromUsername200Response.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this GetUuidFromUsername200Response.

        UUID of user.  # noqa: E501

        :param username: The username of this GetUuidFromUsername200Response.
        :type username: str
        """

        self._username = username
