from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class InventoryItemId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, owner_id=None, item_id=None):  # noqa: E501
        """InventoryItemId - a model defined in OpenAPI

        :param owner_id: The owner_id of this InventoryItemId.  # noqa: E501
        :type owner_id: str
        :param item_id: The item_id of this InventoryItemId.  # noqa: E501
        :type item_id: str
        """
        self.openapi_types = {
            'owner_id': str,
            'item_id': str
        }

        self.attribute_map = {
            'owner_id': 'owner_id',
            'item_id': 'item_id'
        }

        self._owner_id = owner_id
        self._item_id = item_id

    @classmethod
    def from_dict(cls, dikt) -> 'InventoryItemId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InventoryItemId of this InventoryItemId.  # noqa: E501
        :rtype: InventoryItemId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def owner_id(self) -> str:
        """Gets the owner_id of this InventoryItemId.

        UUID of user.  # noqa: E501

        :return: The owner_id of this InventoryItemId.
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id: str):
        """Sets the owner_id of this InventoryItemId.

        UUID of user.  # noqa: E501

        :param owner_id: The owner_id of this InventoryItemId.
        :type owner_id: str
        """

        self._owner_id = owner_id

    @property
    def item_id(self) -> str:
        """Gets the item_id of this InventoryItemId.

        UUID of single item.  # noqa: E501

        :return: The item_id of this InventoryItemId.
        :rtype: str
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: str):
        """Sets the item_id of this InventoryItemId.

        UUID of single item.  # noqa: E501

        :param item_id: The item_id of this InventoryItemId.
        :type item_id: str
        """

        self._item_id = item_id
